### ISSUE TITLE
触发定时任务时候，总是提示以下错误。单独运行用例的时候就可以，不知道是什么情况

### ISSUE THREAD

**Issue by Solomon-hjf** [tahitimoon/LunarLink#16]
Internal Server Error: /api/lunarlink/schedule/3
Traceback (most recent call last):
  File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\utils\functional.py", line 30, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\connection.py", line 446, in _reraise_as_library_errors
    yield
  File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\connection.py", line 433, in _ensure_connection
    return retry_over_time(
  File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\utils\functional.py", line 312, in retry_over_time
    return fun(*args, **kwargs)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\connection.py", line 877, in _connection_factory
    self._connection = self._establish_connection()
  File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\connection.py", line 812, in _establish_connection
    conn = self.transport.establish_connection()
  File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\transport\pyamqp.py", line 201, in establish_connection
    conn.connect()
  File "F:\LunarLink-main\backend\venv\lib\site-packages\amqp\connection.py", line 323, in connect
    self.transport.connect()
  File "F:\LunarLink-main\backend\venv\lib\site-packages\amqp\transport.py", line 129, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\amqp\transport.py", line 184, in _connect
    self.sock.connect(sa)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\LunarLink-main\backend\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "F:\LunarLink-main\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "E:\git\atp-backend\apps\lunarlink\utils\decorator.py", line 38, in inner_wrapper
    return func(request, *args, **kwargs)
  File "E:\git\atp-backend\apps\lunarlink\views\schedule.py", line 222, in run
    app.send_task(
  File "F:\LunarLink-main\backend\venv\lib\site-packages\celery\app\base.py", line 789, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\celery\app\amqp.py", line 510, in send_task_message
    ret = producer.publish(
  File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\messaging.py", line 177, in publish
    return _publish(
  File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\connection.py", line 523, in _ensured
    return fun(*args, **kwargs)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\messaging.py", line 186, in _publish
    channel = self.channel
  File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\messaging.py", line 209, in _get_channel
    channel = self._channel = channel()
  File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\utils\functional.py", line 32, in __call__
    value = self.__value__ = self.__contract__()
  File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\messaging.py", line 225, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\connection.py", line 895, in default_channel
    self._ensure_connection(**conn_opts)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\connection.py", line 433, in _ensure_connection
    return retry_over_time(
  File "D:\lague\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\connection.py", line 450, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\LunarLink-main\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\django\core\handlers\base.py", line 183, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\django\core\handlers\base.py", line 339, in process_exception_by_middleware
    response = middleware_method(request, exception)
  File "E:\git\atp-backend\backend\utils\middleware.py", line 121, in process_exception
    qy_message.send(msg=message_dict)
  File "E:\git\atp-backend\apps\lunarlink\utils\qy_message.py", line 71, in send
    res = requests.post(url=webhook, headers=header, json=data).json()
  File "F:\LunarLink-main\backend\venv\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "F:\LunarLink-main\backend\venv\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "F:\LunarLink-main\backend\venv\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2024-06-07 15:39:57,096 [618fb1f7c91b4b1ea0b994b9e985148b] django.server ERROR [pid:28344] [basehttp.py->log_message:161] "GET /api/lunarlink/schedule/3 HTTP/1.1" 500 34692

**Comment by tahitimoon** [comment]
> Internal Server Error: /api/lunarlink/schedule/3 Traceback (most recent call last): File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\utils\functional.py", line 30, in **call** return self.**value** AttributeError: 'ChannelPromise' object has no attribute '**value**'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\connection.py", line 446, in _reraise_as_library_errors yield File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\connection.py", line 433, in _ensure_connection return retry_over_time( File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\utils\functional.py", line 312, in retry_over_time return fun(*args, **kwargs) File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\connection.py", line 877, in _connection_factory self._connection = self._establish_connection() File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\connection.py", line 812, in _establish_connection conn = self.transport.establish_connection() File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\transport\pyamqp.py", line 201, in establish_connection conn.connect() File "F:\LunarLink-main\backend\venv\lib\site-packages\amqp\connection.py", line 323, in connect self.transport.connect() File "F:\LunarLink-main\backend\venv\lib\site-packages\amqp\transport.py", line 129, in connect self._connect(self.host, self.port, self.connect_timeout) File "F:\LunarLink-main\backend\venv\lib\site-packages\amqp\transport.py", line 184, in _connect self.sock.connect(sa) socket.timeout: timed out
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "F:\LunarLink-main\backend\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response response = wrapped_callback(request, *callback_args, **callback_kwargs) File "F:\LunarLink-main\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view return view_func(*args, **kwargs) File "F:\LunarLink-main\backend\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view return self.dispatch(request, *args, **kwargs) File "F:\LunarLink-main\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch response = self.handle_exception(exc) File "F:\LunarLink-main\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception self.raise_uncaught_exception(exc) File "F:\LunarLink-main\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception raise exc File "F:\LunarLink-main\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch response = handler(request, *args, **kwargs) File "F:\LunarLink-main\backend\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper return bound_method(*args, **kwargs) File "E:\git\atp-backend\apps\lunarlink\utils\decorator.py", line 38, in inner_wrapper return func(request, *args, **kwargs) File "E:\git\atp-backend\apps\lunarlink\views\schedule.py", line 222, in run app.send_task( File "F:\LunarLink-main\backend\venv\lib\site-packages\celery\app\base.py", line 789, in send_task amqp.send_task_message(P, name, message, **options) File "F:\LunarLink-main\backend\venv\lib\site-packages\celery\app\amqp.py", line 510, in send_task_message ret = producer.publish( File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\messaging.py", line 177, in publish return _publish( File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\connection.py", line 523, in _ensured return fun(*args, **kwargs) File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\messaging.py", line 186, in _publish channel = self.channel File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\messaging.py", line 209, in _get_channel channel = self._channel = channel() File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\utils\functional.py", line 32, in **call** value = self.**value** = self.**contract**() File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\messaging.py", line 225, in channel = ChannelPromise(lambda: connection.default_channel) File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\connection.py", line 895, in default_channel self._ensure_connection(**conn_opts) File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\connection.py", line 433, in _ensure_connection return retry_over_time( File "D:\lague\Python39\lib\contextlib.py", line 137, in **exit** self.gen.throw(typ, value, traceback) File "F:\LunarLink-main\backend\venv\lib\site-packages\kombu\connection.py", line 450, in _reraise_as_library_errors raise ConnectionError(str(exc)) from exc kombu.exceptions.OperationalError: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "F:\LunarLink-main\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner response = get_response(request) File "F:\LunarLink-main\backend\venv\lib\site-packages\django\core\handlers\base.py", line 183, in _get_response response = self.process_exception_by_middleware(e, request) File "F:\LunarLink-main\backend\venv\lib\site-packages\django\core\handlers\base.py", line 339, in process_exception_by_middleware response = middleware_method(request, exception) File "E:\git\atp-backend\backend\utils\middleware.py", line 121, in process_exception qy_message.send(msg=message_dict) File "E:\git\atp-backend\apps\lunarlink\utils\qy_message.py", line 71, in send res = requests.post(url=webhook, headers=header, json=data).json() File "F:\LunarLink-main\backend\venv\lib\site-packages\requests\api.py", line 115, in post return request("post", url, data=data, json=json, **kwargs) File "F:\LunarLink-main\backend\venv\lib\site-packages\requests\api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "F:\LunarLink-main\backend\venv\lib\site-packages\requests\sessions.py", line 573, in request prep = self.prepare_request(req) File "F:\LunarLink-main\backend\venv\lib\site-packages\requests\sessions.py", line 484, in prepare_request p.prepare( File "F:\LunarLink-main\backend\venv\lib\site-packages\requests\models.py", line 368, in prepare self.prepare_url(url, params) File "F:\LunarLink-main\backend\venv\lib\site-packages\requests\models.py", line 439, in prepare_url raise MissingSchema( requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://? 2024-06-07 15:39:57,096 [618fb1f7c91b4b1ea0b994b9e985148b] django.server ERROR [pid:28344] [basehttp.py->log_message:161] "GET /api/lunarlink/schedule/3 HTTP/1.1" 500 34692

还是库版本的原因，最好在本地创建python虚拟环境，单独使用pip install -r requirements.txt安装依赖库
